from transformers import pipeline
import argparse

# Load the summarization pipeline with a pre-trained model
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# Example text passage
text1 = """Climate change refers to long-term shifts in temperatures and weather patterns. 
These shifts may be natural, but since the 1800s, human activities have been the main driver 
of climate change, primarily due to burning fossil fuels like coal, oil, and gas. 
Burning fossil fuels generates greenhouse gas emissions that trap heat in the Earth's atmosphere, 
causing global temperatures to rise."""

text2 = """Artificial intelligence (AI) is a branch of computer science that aims to create machines capable of intelligent behavior. 
AI technologies are used in a variety of fields, including healthcare, finance, education, and transportation. 
By analyzing large amounts of data, AI systems can recognize patterns, make predictions, and automate complex tasks, 
leading to increased efficiency and new possibilities in many industries."""

text3 = """The Internet of Things (IoT) is a rapidly growing network of interconnected devices that communicate and exchange data with each other through the internet. 
These devices, which include everything from household appliances and wearable fitness trackers to industrial sensors and smart vehicles, are embedded with sensors, software, and other technologies that enable them to collect and transmit data. 
IoT has revolutionized many aspects of daily life and industry by enabling automation, improving efficiency, and providing real-time insights. 
For example, in smart homes, IoT devices can control lighting, heating, and security systems remotely, while in healthcare, wearable devices can monitor patients’ vital signs and alert medical professionals to potential issues. 
In agriculture, IoT sensors help farmers monitor soil conditions and optimize irrigation, leading to better crop yields. 
Despite its many benefits, IoT also raises concerns about data privacy and security, as the vast amount of data generated by these devices can be vulnerable to cyberattacks if not properly protected. 
As IoT technology continues to evolve, it is expected to play an increasingly important role in shaping the future of society, industry, and the global economy."""
# Generate the summary
parser = argparse.ArgumentParser(description="Summarize text with custom summary length range.")
parser.add_argument("--range", type=str, default="20-80", help="Summary length range as min-max (default: 20-50)")
args = parser.parse_args()

try:
    min_length, max_length = map(int, args.range.split('-'))
except Exception:
    parser.error("Range must be in the format min-max, e.g., 20-50")
summary = summarizer(text1, max_length=max_length, min_length=min_length, do_sample=False)


# Print the summarized output
print(summary[0]['summary_text'])
